import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import logo from "./assets/bwr.png";

const NAV_LINKS = ["Home", "Services", "Gallery", "Reviews", "Schedule a Tour", "Career", "Privacy Policy"];

const SECTIONS = [
  {
    id: "intro",
    title: "Privacy Policy",
    content: [
      {
        type: "text",
        body: "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
      },
      {
        type: "text",
        body: "We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.",
      },
    ],
  },
  {
    id: "regulation",
    title: "Washington State Regulation",
    content: [
      {
        type: "text",
        body: "Blessed Hill Adult Family Home is regulated by the state of Washington under the law RCW 70.128.130. In addition to the Health Insurance Portability and Accountability Act of 1996 (HIPAA), please review the full privacy policy below.",
      },
    ],
  },
  {
    id: "interpretation",
    title: "Interpretation",
    content: [
      {
        type: "text",
        body: "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
      },
    ],
  },
  {
    id: "definitions",
    title: "Definitions",
    content: [
      {
        type: "definitions",
        items: [
          { term: "Account", def: "A unique account created for You to access our Service or parts of our Service." },
          { term: "Affiliate", def: 'An entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.' },
          { term: "Company", def: 'Referred to as either "the Company", "We", "Us" or "Our" in this Agreement — refers to Blessed Hill Adult Family Home LLC, 11803 SE 323rd PL, Auburn, WA 98092.' },
          { term: "Cookies", def: "Small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses." },
          { term: "Country", def: "Washington, United States." },
          { term: "Device", def: "Any device that can access the Service such as a computer, a cellphone or a digital tablet." },
          { term: "Personal Data", def: "Any information that relates to an identified or identifiable individual." },
          { term: "Service", def: "Refers to the Website." },
          { term: "Service Provider", def: "Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used." },
          { term: "Usage Data", def: "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." },
        ],
      },
    ],
  },
];

export default function BlessedHillPrivacyPolicy({ navigate = () => {} }) {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);

  useEffect(() => {
    const fn = () => setScrolled(window.scrollY > 40);
    window.addEventListener("scroll", fn, { passive: true });
    return () => window.removeEventListener("scroll", fn);
  }, []);

  return (
    <div style={{ fontFamily:"'Playfair Display',Georgia,serif", background:"#faf8f4", minHeight:"100vh", overflowX:"hidden" }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400&family=DM+Sans:wght@300;400;500;600&display=swap');
        *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
        :root{
          --bd:#1a3a5c;--bm:#2e6da4;--bs:#5b9bd5;
          --cr:#faf8f4;--cd:#f0ece2;--wh:#ffffff;
          --tm:#4a6278;--tl:#8a9dae;
          --gd:#c9a84c;--br:rgba(30,80,140,0.09);--rd:14px;
        }
        .sans{font-family:'DM Sans',sans-serif}

        /* NAV */
        .nav {
          position: fixed; top: 0; left: 0; right: 0; z-index: 100;
          background: rgba(255,255,255,0.97);
          backdrop-filter: blur(12px);
          box-shadow: 0 2px 24px rgba(30,80,140,0.10);
          transition: background 0.4s ease, box-shadow 0.4s ease;
          padding: 0 48px;
        }
        .nav.scrolled {
          background: rgba(255,255,255,0.97);
          backdrop-filter: blur(12px);
          box-shadow: 0 2px 24px rgba(30,80,140,0.10);
        }
        .nav-inner {
          max-width: 1280px; margin: 0 auto;
          display: flex; align-items: center; justify-content: space-between;
          gap: 80px;
          height: 72px;
        }
        .nav-logo { display: flex; flex-direction: column; }
        .nav-logo-main {
          font-family: 'Playfair Display', serif;
          font-size: 26px; font-weight: 800; line-height: 1.1; letter-spacing: -0.3px;
          color: var(--bd);
        }
        .nav-logo-sub {
          font-family: 'DM Sans', sans-serif;
          font-size: 14px; letter-spacing: 1.5px; text-transform: uppercase;
          color: var(--bs);
        }        .nlm{font-family:'Playfair Display',serif;font-size:18px;font-weight:700;color:var(--bd);cursor:pointer}
        .nls{font-family:'DM Sans',sans-serif;font-size:10px;color:var(--bs);letter-spacing:1.5px;text-transform:uppercase}
        .nl{display:flex;gap:28px;list-style:none}
        .nl a{font-family:'DM Sans',sans-serif;font-size:13.5px;font-weight:500;color:var(--tm);text-decoration:none;transition:color .2s}
        .nl a:hover{color:var(--bm)}
        .nl a.active{color:var(--bd);font-weight:600;border-bottom:2px solid var(--gd);padding-bottom:2px}
        .ncta{background:var(--bd);color:white;font-family:'DM Sans',sans-serif;font-size:13px;font-weight:500;border:none;border-radius:50px;padding:9px 22px;cursor:pointer;transition:background .2s,transform .2s}
        .ncta:hover{background:var(--bm);transform:translateY(-1px)}

        /* PAGE HEADER */
        .page-header{
          padding:140px 48px 64px;
          background:var(--cd);
          border-bottom:1px solid rgba(201,168,76,.15);
          position:relative;overflow:hidden;
        }
        .page-header::before{
          content:'';position:absolute;inset:0;
          background-image:radial-gradient(circle,rgba(30,80,140,0.05) 1px,transparent 1px);
          background-size:28px 28px;pointer-events:none;
        }
        .header-inner{max-width:880px;margin:0 auto;position:relative;z-index:1}
        .header-kicker{font-family:'DM Sans',sans-serif;font-size:11px;font-weight:600;letter-spacing:3px;text-transform:uppercase;color:var(--gd);display:flex;align-items:center;gap:12px;margin-bottom:16px}
        .header-kicker::before{content:'';display:block;width:28px;height:1.5px;background:var(--gd)}
        .header-title{font-size:clamp(36px,5vw,60px);font-weight:700;color:var(--bd);line-height:1.05;letter-spacing:-1.5px;margin-bottom:14px}
        .header-date{font-family:'DM Sans',sans-serif;font-size:13px;color:var(--tl);display:flex;align-items:center;gap:8px}
        .header-date::before{content:'';display:block;width:16px;height:1px;background:var(--tl)}

        /* BODY LAYOUT */
        .body-wrap{
          max-width:1100px;margin:0 auto;padding:64px 48px 80px;
          display:grid;grid-template-columns:220px 1fr;gap:64px;align-items:start;
        }

        /* STICKY TOC */
        .toc{position:sticky;top:104px}
        .toc-label{font-family:'DM Sans',sans-serif;font-size:10px;font-weight:600;letter-spacing:2px;text-transform:uppercase;color:var(--tl);margin-bottom:16px}
        .toc-list{list-style:none;display:flex;flex-direction:column;gap:2px}
        .toc-item a{
          display:block;font-family:'DM Sans',sans-serif;font-size:13px;font-weight:500;
          color:var(--tl);text-decoration:none;padding:7px 12px;border-radius:8px;
          border-left:2px solid transparent;transition:all .2s;
        }
        .toc-item a:hover{color:var(--bm);background:rgba(46,109,164,.05);border-left-color:var(--bs)}
        .toc-divider{height:1px;background:var(--br);margin:16px 0}
        .toc-contact{font-family:'DM Sans',sans-serif;font-size:12px;color:var(--tl);line-height:1.7}
        .toc-contact a{color:var(--bm);text-decoration:none}
        .toc-contact a:hover{text-decoration:underline}

        /* CONTENT */
        .content{min-width:0}
        .policy-section{
          margin-bottom:52px;padding-bottom:52px;
          border-bottom:1px solid var(--br);
        }
        .policy-section:last-child{border-bottom:none;margin-bottom:0;padding-bottom:0}
        .section-title{
          font-size:22px;font-weight:700;color:var(--bd);
          letter-spacing:-.3px;margin-bottom:18px;
          display:flex;align-items:center;gap:12px;
        }
        .section-title::before{content:'';display:block;width:4px;height:22px;background:var(--gd);border-radius:2px;flex-shrink:0}
        .section-body{
          font-family:'DM Sans',sans-serif;font-size:15.5px;font-weight:300;
          color:var(--tm);line-height:1.85;
        }
        .section-body + .section-body{margin-top:14px}

        /* Definitions list */
        .def-list{display:flex;flex-direction:column;gap:0}
        .def-item{
          display:grid;grid-template-columns:180px 1fr;gap:24px;
          padding:16px 0;border-bottom:1px solid var(--br);
          align-items:baseline;
        }
        .def-item:last-child{border-bottom:none}
        .def-term{
          font-family:'DM Sans',sans-serif;font-size:13px;font-weight:700;
          color:var(--bd);letter-spacing:.3px;
        }
        .def-def{
          font-family:'DM Sans',sans-serif;font-size:14.5px;font-weight:300;
          color:var(--tm);line-height:1.75;
        }

        /* Regulation highlight box */
        .reg-box{
          background:rgba(46,109,164,.06);border:1px solid rgba(46,109,164,.15);
          border-left:4px solid var(--bm);
          border-radius:0 var(--rd) var(--rd) 0;
          padding:20px 24px;
          font-family:'DM Sans',sans-serif;font-size:15px;font-weight:300;
          color:var(--tm);line-height:1.8;
        }
        .reg-box a{color:var(--bm);text-decoration:none;font-weight:500}
        .reg-box a:hover{text-decoration:underline}

        /* FOOTER */
        .footer{background:#0b1a27;color:rgba(255,255,255,.55);padding:52px 48px 28px;font-family:'DM Sans',sans-serif;font-size:13.5px}
        .footer-inner{max-width:1280px;margin:0 auto;display:grid;grid-template-columns:2fr 1fr 1fr;gap:60px;padding-bottom:40px;border-bottom:1px solid rgba(255,255,255,.07)}
        .fbr{font-family:'Playfair Display',serif;font-size:18px;font-weight:700;color:white;margin-bottom:10px}
        .fbd{line-height:1.8;max-width:300px;margin-bottom:16px}
        .fbt{color:var(--gd);font-weight:500;text-decoration:none;font-size:15px}
        .fbt:hover{text-decoration:underline}
        .fch{color:white;font-weight:600;font-size:14px;margin-bottom:16px}
        .fl{list-style:none;display:flex;flex-direction:column;gap:9px}
        .fl a{color:rgba(255,255,255,.5);text-decoration:none;transition:color .2s}
        .fl a:hover{color:white}
        .fbot{max-width:1280px;margin:0 auto;padding-top:22px;display:flex;justify-content:space-between;align-items:center;font-size:12px;color:rgba(255,255,255,.28)}
        .hamburger{
          display:none;background:none;border:none;
          font-size:22px;cursor:pointer;color:var(--bd);
          padding:8px;align-items:center;justify-content:center;
          min-width:44px;min-height:44px;border-radius:8px;
        }
        /* RESPONSIVE */
        @media(max-width:900px){
          .nav{padding:0 20px}
          .nl,.ncta{display:none}
          .hamburger{display:flex}
          .nav-inner{height:64px;gap:12px}
          .nav-logo-img{height:52px !important}
          .nav-logo-main{font-size:16px}
          .nav-logo-sub{font-size:10px}
          .page-header{padding:120px 24px 52px}
          .body-wrap{grid-template-columns:1fr;padding:40px 24px 60px;gap:40px}
          .toc{position:static;display:flex;flex-wrap:wrap;gap:8px;align-items:center}
          .toc-label{display:none}
          .toc-list{flex-direction:row;flex-wrap:wrap;gap:4px}
          .toc-divider,.toc-contact{display:none}
          .def-item{grid-template-columns:1fr;gap:4px}
          .footer{padding:44px 24px 24px}
          .footer-inner{grid-template-columns:1fr;gap:32px}
          .fbot{flex-direction:column;gap:6px;text-align:center}
        }
        @media(max-width:540px){
          .nav-inner{height:56px;gap:8px}
          .nav-logo-img{height:44px !important}
        }
        /* MOBILE MENU — full-screen overlay (matches Gallery) */
        .mobile-menu{
          position:fixed; top:0; left:0; right:0; bottom:0;
          z-index:100;
          background:rgba(13,33,55,0.98);
          backdrop-filter:blur(12px);
          display:flex; flex-direction:column;
          align-items:center; justify-content:flex-start;
          gap:8px;
          overflow-y:auto;
          padding:80px 24px 40px;
        }
        .mobile-menu-close{
          position:absolute;top:20px;right:20px;
          background:none;border:none;
          font-size:24px;color:rgba(255,255,255,0.7);
          cursor:pointer;padding:8px;
          min-width:44px;min-height:44px;
          display:flex;align-items:center;justify-content:center;
        }
        .mobile-link{
          font-family:'DM Sans',sans-serif;font-size:20px;font-weight:400;
          color:rgba(255,255,255,0.85);text-decoration:none;
          padding:14px 32px;border-radius:12px;
          width:100%;max-width:320px;text-align:center;
          transition:background 0.2s,color 0.2s;
        }
        .mobile-link:hover{background:rgba(255,255,255,0.08);color:white}
        .mobile-link.active-link{color:var(--gd);font-weight:500}
      `}</style>

      {/* NAV */}
      <nav className={`nav${scrolled?" scrolled":""}`}>
        <div className="nav-inner">
          <div onClick={()=>navigate("Home")} style={{display:"flex", alignItems:"center", gap:"0px", cursor:"pointer", marginLeft:"-15px"}}>
            <img src={logo} alt="Blessed Hill" className="nav-logo-img" style={{height:"140px", width:"auto"}} />
            <div>
              <div className="nav-logo-main">Blessed Hill</div>
              <div className="nav-logo-sub sans">Adult Family Home</div>
            </div>
          </div>
          <ul className="nl">
            {NAV_LINKS.map((label) => (
              <li key={label}>
                <a href="#" className={label==="Privacy Policy"?"active":""} onClick={e=>{e.preventDefault();navigate(label);}}>
                  {label}
                </a>
              </li>
            ))}
          </ul>
          
          <button className="hamburger" style={{marginLeft:"auto"}}onClick={()=>setMenuOpen(o=>!o)} aria-label="Menu">
            {menuOpen ? "✕" : "☰"}
          </button>
        </div>
      </nav>
      <AnimatePresence>
      {menuOpen && (
      <motion.div 
        className="mobile-menu"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        transition={{ duration: 0.25, ease: "easeOut" }}
      >
        <button className="mobile-menu-close" onClick={()=>setMenuOpen(false)} aria-label="Close menu">✕</button>
        {NAV_LINKS.map((l, i) => (
          <motion.a 
            key={l} 
            href="#" 
            className={`mobile-link sans${l==="Privacy Policy" ? " active-link" : ""}`} 
            onClick={e=>{e.preventDefault();navigate(l);setMenuOpen(false);}}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.05, duration: 0.3 }}
          >
            {l}
          </motion.a>
        ))}
      </motion.div>
      )}
      </AnimatePresence>

      {/* PAGE HEADER */}
      <header className="page-header">
        <div className="header-inner">
          <p className="header-kicker sans">Legal</p>
          <h1 className="header-title">Privacy Policy</h1>
          <p className="header-date sans">Last updated: January 23, 2024</p>
        </div>
      </header>

      {/* BODY */}
      <div className="body-wrap">

        {/* TABLE OF CONTENTS */}
        <aside className="toc">
          <p className="toc-label sans">On this page</p>
          <ul className="toc-list">
            {SECTIONS.map(s=>(
              <li key={s.id} className="toc-item">
                <a href={`#${s.id}`} onClick={e=>{e.preventDefault();document.getElementById(s.id)?.scrollIntoView({behavior:"smooth",block:"start"})}}>
                  {s.title}
                </a>
              </li>
            ))}
          </ul>
          <div className="toc-divider" />
          <div className="toc-contact sans">
            Questions?<br />
            <a href="tel:12533974881">253-397-4881</a><br />
            11803 SE 323rd PL<br />Auburn, WA 98092
          </div>
        </aside>

        {/* POLICY CONTENT */}
        <main className="content">

          {/* Regulation highlight */}
          <div className="reg-box sans" style={{marginBottom:48}}>
            We are regulated by the state of Washington under the law{" "}
            <a href="https://app.leg.wa.gov/rcw/default.aspx?cite=70.128.130" target="_blank" rel="noreferrer">RCW 70.128.130</a>.
            In addition to the{" "}
            <a href="https://www.hhs.gov/hipaa/index.html" target="_blank" rel="noreferrer">
              Health Insurance Portability and Accountability Act
            </a>{" "}
            of 1996 (HIPAA), please review our full privacy policy below.
          </div>

          {SECTIONS.map(section=>(
            <div key={section.id} id={section.id} className="policy-section" style={{scrollMarginTop:112}}>
              <h2 className="section-title">{section.title}</h2>
              {section.content.map((block, i)=>{
                if (block.type === "text") {
                  return <p key={i} className="section-body">{block.body}</p>;
                }
                if (block.type === "definitions") {
                  return (
                    <dl key={i} className="def-list">
                      {block.items.map(item=>(
                        <div key={item.term} className="def-item">
                          <dt className="def-term sans">{item.term}</dt>
                          <dd className="def-def sans">{item.def}</dd>
                        </div>
                      ))}
                    </dl>
                  );
                }
                return null;
              })}
            </div>
          ))}

        </main>
      </div>

      {/* FOOTER */}
      <footer className="footer">
        <div className="footer-inner">
          <div>
            <div className="fbr">Blessed Hill Adult Family Home</div>
            <p className="fbd">Licensed residential adult care in Auburn, WA — guided by Christian values and a deep commitment to dignity.</p>
            <a href="tel:12533974881" className="fbt">253-397-4881</a>
          </div>
          <div>
            <div className="fch">Quick Links</div>
            <ul className="fl">
              {NAV_LINKS.map(l=><li key={l}><a href="#" onClick={e=>{e.preventDefault();navigate(l);}}>{l}</a></li>)}
            </ul>
          </div>
          <div>
            <div className="fch">Find Us</div>
            <address style={{fontStyle:"normal",lineHeight:1.9,color:"rgba(255,255,255,.5)"}}>
              11803 SE 323rd PL<br/>Auburn, WA 98092<br/><br/>
              <a href="tel:12533974881" style={{color:"rgba(255,255,255,.5)",textDecoration:"none"}}>253-397-4881</a>
            </address>
          </div>
        </div>
        <div className="fbot sans">
          <span>© 2026 Blessed Hill Adult Family Home, LLC. All rights reserved.</span>
          <a href="#" onClick={e=>{e.preventDefault();navigate("privacy")}} style={{color:"rgba(255,255,255,.28)",textDecoration:"none"}}>Privacy Policy</a>
        </div>
      </footer>

    </div>
  );
}
